name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

  workflow_dispatch:

concurrency:
  group: ci-pull-request
  cancel-in-progress: true

  analize:
    name: '🔎 Analize'
    uses: ./.github/workflows/_analize.yml
    if:  ${{ !startsWith(github.head_ref, 'renovate/') && github.event.pull_request.draft == false }}

  test:
    name: '🧪 Test'
    uses: ./.github/workflows/_test.yml
    if:  ${{ !startsWith(github.head_ref, 'renovate/') && github.event.pull_request.draft == false }}
